### PR TITLE
Fix profiling plugin.

### LINKED ISSUE #281: GC profiling plugin error when test namespace fails to load
Applies to version 1.64.1010.

When running a test suite via the CLI runner with the `:kaocha.plugin/gc-profiling` plugin enabled and an error occurs during loading of a test namespace (e.g. due to a syntax error), the runner terminates with the following error from the `gc-profiling` plugin:

```
Execution error (ArityException) at kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook (gc_profiling.clj:72).
Wrong number of args (0) passed to: kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook/fn--4568

Full report at:
/tmp/clojure-16823613534631527829.edn
```

Full report (GitHub doesn't allow uploading as attachment):

```clojure
{:clojure.main/message
 "Execution error (ArityException) at kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook (gc_profiling.clj:72).\nWrong number of args (0) passed to: kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook/fn--4568\n",
 :clojure.main/triage
 {:clojure.error/class clojure.lang.ArityException,
  :clojure.error/line 72,
  :clojure.error/cause
  "Wrong number of args (0) passed to: kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook/fn--4568",
  :clojure.error/symbol
  kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook,
  :clojure.error/source "gc_profiling.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ArityException,
    :message
    "Wrong number of args (0) passed to: kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook/fn--4568",
    :at [clojure.lang.AFn throwArity "AFn.java" 429]}],
  :trace
  [[clojure.lang.AFn throwArity "AFn.java" 429]
   [clojure.lang.AFn invoke "AFn.java" 28]
   [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 28]
   [clojure.core.protocols$fn__8236 invokeStatic "protocols.clj" 75]
   [clojure.core.protocols$fn__8236 invoke "protocols.clj" 75]
   [clojure.core.protocols$fn__8178$G__8173__8191
    invoke
    "protocols.clj"
    13]
   [clojure.core$reduce invokeStatic "core.clj" 6882]
   [clojure.core$reduce invoke "core.clj" 6868]
   [kaocha.plugin.gc_profiling$gc_profiling_post_summary_hook
    invokeStatic
    "gc_profiling.clj"
    72]
   [kaocha.plugin.gc_profiling$gc_profiling_post_summary_hook
    invoke
    "gc_profiling.clj"
    36]
   [clojure.lang.AFn applyToHelper "AFn.java" 154]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.core$apply invokeStatic "core.clj" 669]
   [clojure.core$apply invoke "core.clj" 662]
   [kaocha.plugin$run_hook_STAR_$fn__2172 invoke "plugin.clj" 91]
   [clojure.lang.PersistentVector reduce "PersistentVector.java" 343]
   [clojure.core$reduce invokeStatic "core.clj" 6885]
   [clojure.core$reduce invoke "core.clj" 6868]
   [kaocha.plugin$run_hook_STAR_ invokeStatic "plugin.clj" 89]
   [kaocha.plugin$run_hook_STAR_ doInvoke "plugin.clj" 88]
   [clojure.lang.RestFn invoke "RestFn.java" 445]
   [clojure.lang.AFn applyToHelper "AFn.java" 160]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.core$apply invokeStatic "core.clj" 673]
   [clojure.core$apply invoke "core.clj" 662]
   [kaocha.plugin$run_hook invokeStatic "plugin.clj" 100]
   [kaocha.plugin$run_hook doInvoke "plugin.clj" 99]
   [clojure.lang.RestFn invoke "RestFn.java" 425]
   [kaocha.runner$run$fn__3988 invoke "runner.clj" 132]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1990]
   [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1990]
   [clojure.lang.RestFn invoke "RestFn.java" 425]
   [kaocha.runner$run invokeStatic "runner.clj" 130]
   [kaocha.runner$run invoke "runner.clj" 73]
   [kaocha.runner$_main_STAR_ invokeStatic "runner.clj" 176]
   [kaocha.runner$_main_STAR_ doInvoke "runner.clj" 144]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$apply invoke "core.clj" 662]
   [kaocha.runner$_main invokeStatic "runner.clj" 187]
   [kaocha.runner$_main doInvoke "runner.clj" 185]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Wrong number of args (0) passed to: kaocha.plugin.gc-profiling/gc-profiling-post-summary-hook/fn--4568"}}
```

### PR DESCRIPTION
**Pull request by alysbrooks**
Fixes #281. Apparently, syntax errors prevent tests from running, so there's no results to calculate the length of in `post-summary`. I wasn't able to reproduce the original bug directly, but I was able to reproduce the issue with the anonymous function.

### CODE REVIEW

File: src/kaocha/plugin/gc_profiling.clj [hunk 1]
```diff
@@ -46,7 +46,7 @@
   (post-test [testable _]
     (stop testable))
 
-  (cli-options [opts]
+ (cli-options [opts]
```
Comment (plexus) [inline src/kaocha/plugin/gc_profiling.clj:49]: Whitespace, please!

File: src/kaocha/plugin/gc_profiling.clj [hunk 2]
```diff
@@ -69,7 +69,9 @@
                 longest  (->> tests
                               (map :kaocha.testable/id) 
                               (map count)
-                              (reduce (fn [a b] (Math/max a b)))
+                              (reduce (fn
```
Comment (plexus) [inline src/kaocha/plugin/gc_profiling.clj:72]: You could also pass an initial value explicitly to `reduce`

```clojure
(reduce (fn [a b] (Math/max a b)) 0 coll)
```
