### PR TITLE
Make sure we can still run Kaocha when test.check is not available

### LINKED ISSUE #159: test.check.generators FileNotFoundException after upgrading to 1.0.700
After updating to `[lambdaisland/kaocha "1.0.700"]`, I started receiving the following:

```bash
$ bin/kaocha                                                                                                                                                                                                                                           
Execution error (FileNotFoundException) at kaocha.specs/fn (specs.clj:82).
Could not locate clojure/test/check/generators__init.class, clojure/test/check/generators.clj or clojure/test/check/generators.cljc on classpath.
```

It seems to have been caused by these additions:
https://github.com/lambdaisland/kaocha/commit/b0c6b1fe795a2b8e91ded58756689dc372fe31ee#diff-2ed781d06f75f1466a634ea0794d8dbe
https://github.com/lambdaisland/kaocha/commit/552b977065786ce90c7cf9e1611943ac4eb88756

### PR DESCRIPTION
**Pull request by plexus**
Use wrappers for `s/gen` and `s/with-gen`, when we are unable to load
test.check.generators we use simple stubs.

Fixes #159

### CODE REVIEW

**Comment by alysbrooks** [comment]
Looks good. 

I did run into this error when trying to run kaocha tests using this branch without having test.check on my classpath:

```
--- unit (clojure.test) ---------------------------Execution error (FileNotFoundException) at orchestra.spec.test/spec-checking-fn$conform! (test.cljc:15).
Could not locate clojure/test/check/generators__init.class, clojure/test/check/generators.clj or clojure/test/check/generators.cljc on classpath.
```

I don't know if that's arising from a place in kaocha that depends on test.check and shouldn't or is just one of kaocha's tests that depends on test.check. I think it might be the latter and not a problem? In any case, this PR already fixes many of the places I've noticed #159, so perhaps that shouldn't hold up merging this.

One suggestion: Would it make more sense to put the definitions of `s-gen` and `s-with-gen` inside the `catch`? I think they're functionally identical, but it might be clearer. Also, it reduces the odds of the fallback definitions being separated from the regular ones.

**Review by alysbrooks — COMMENTED** [review]
Changes look good! I did have a suggestion I made in line.

I did run into this error when trying to run kaocha tests using this branch without having test.check on my classpath:

```
--- unit (clojure.test) ---------------------------Execution error (FileNotFoundException) at orchestra.spec.test/spec-checking-fn$conform! (test.cljc:15).
Could not locate clojure/test/check/generators__init.class, clojure/test/check/generators.clj or clojure/test/check/generators.cljc on classpath.
```

I don't know if that's arising from a place in kaocha that depends on test.check and shouldn't or is just one of kaocha's tests that depends on test.check. I think it might be the latter and not a problem? In any case, this PR already fixes many of the places I've noticed #159, so perhaps that shouldn't hold up merging this.

File: src/kaocha/specs.clj [hunk 1]
```diff
@@ -4,8 +4,13 @@
...
   (:import (java.io FileNotFoundException)))
 
+(defn s-gen [_])
+(defn s-with-gen [spec _] spec)
+
 (try
   (require 'clojure.test.check.generators)
+  (def s-gen @(resolve 'clojure.spec.alpha/gen))
+  (def s-with-gen @(resolve 'clojure.spec.alpha/with-gen))
   (catch FileNotFoundException _))
```
Comment (alysbrooks) [inline src/kaocha/specs.clj:14]: Would it make more sense to put the definitions of s-gen and s-with-gen here? I think they're functionally identical, but it might be clearer. Also, it reduces the odds of the fallback definitions being separated from the regular ones.
```suggestion
  (catch FileNotFoundException _
  (defn s-gen [_])
  (defn s-with-gen [spec _] spec)))
```

Comment (plexus) [reply src/kaocha/specs.clj:14]: I think having them at the top level may be beneficial for people using tools that rely on static analysis (i.e. Cursive). Not sure if it's smart enough to infer that `s-gen` and `s-with-gen` exist otherwise.
